### ISSUE TITLE
FATA[0000] rpc error: code = Unknown desc = multiple application sources defined: Helm,Plugin

### ISSUE THREAD

**Issue by clcchai** [IBM/argocd-vault-plugin#101] opened 2021-03-17 09:54 UTC
**Is your feature request related to a problem? Please describe.**
Below is whats working
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: your-application-name
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: .
    plugin:
      name: argocd-vault-plugin
    repoURL: http://your-repo/
    targetRevision: HEAD
  project: default
```

However, if we want to use source as helm type instead of plain yamls, ie argo application that is of helm source type, and we cant use the plugin together as there is only one type you can use.

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .api }}
  project: {{ .argocdProject }}
  source:
    helm:
      valueFiles:
      - values.yaml
    plugin:
      name: argocd-vault-plugin
    path: {{ .path }}
    repoURL: {{ .repo }}
    targetRevision: {{ .targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
```

```
argocd app create argovault-test --config-management-plugin argocd-vault-plugin \
--repo https://github.com/test/test.git \
--path Cluster/test/cluster-resources  \
--dest-server https://kubernetes.default.svc \
--dest-namespace default \
--values value.yaml
FATA[0000] rpc error: code = Unknown desc = multiple application sources defined: Helm,Plugin
```
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by werne2j** [comment] 2021-03-17 13:07
This is not a problem with the plugin itself but instead an issue with how you are trying to combine multiple application sources like the error says. If you are trying to create an app of apps via helm then you would want something like
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .api }}
  project: {{ .argocdProject }}
  source:
    plugin:
      name: argocd-vault-plugin
    path: {{ .path }}
    repoURL: {{ .repo }}
    targetRevision: {{ .targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
```
And then that file would be in your templates folder with your values files having the information for this template. Then to create the apps you would do
```
argocd app create argovault-test \
--repo https://github.com/test/test.git \
--path Cluster/test/cluster-resources  \
--dest-server https://kubernetes.default.svc \
--dest-namespace default \
--values value.yaml
```
So this would create one app `argovault-test` that has multiple apps inside that then use the argocd-vault-plugin. 

Hopefully that helps

**Comment by clcchai** [comment] 2021-03-17 13:19
hi Jacob,
hmm..
so this part , apps of apps - helm template
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .api }}
  project: {{ .argocdProject }}
  source:
    plugin:
      name: argocd-vault-plugin
    path: {{ .path }}
    repoURL: {{ .repo }}
    targetRevision: {{ .targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
```

where do you define the values.yaml to inform argocd that this is a helm app?

the second part of the above is just the imperative way, so please ignore it

**Comment by clcchai** [comment] 2021-03-17 13:21
eg my helm values.yaml look like this:
```
  - name: cluster-configuration
    namespace: authentication
    argocdProject: bootstrapping
    repo: https://github.com/test/test.git
    path: Cluster/shdvcl1001/applications/cluster-config
    targetRevision: HEAD
    api: https://kubernetes.default.svc
```

**Comment by werne2j** [comment] 2021-03-17 13:48
@clcchai In order to do what you want to do you would have a helm chart that has a structure like this:
```
templates/
  application.yaml
Chart.yaml
values.yaml
```
Where `application.yaml` is
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argo-cd
spec:
  destination:
    namespace: {{ .namespace }}
    server: {{ .api }}
  project: {{ .argocdProject }}
  source:
    plugin:
      name: argocd-vault-plugin
    path: {{ .path }}
    repoURL: {{ .repo }}
    targetRevision: {{ .targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
```
and `values.yaml` is 
```
  - name: cluster-configuration
    namespace: authentication
    argocdProject: bootstrapping
    repo: https://github.com/test/test.git
    path: Cluster/clusterA/applications/cluster-config
    targetRevision: HEAD
    api: https://kubernetes.default.svc
```
Then you would create your argocd app of apps from that helm chart. 
These references may help:
https://github.com/argoproj/argocd-example-apps/tree/master/helm-guestbook
https://argoproj.github.io/argo-cd/operator-manual/cluster-bootstrapping/#app-of-apps-pattern

But i am going to say that this is not an issue with the plugin and will close this issue

**Closed** 2021-03-17 15:44 UTC

**Comment by ira-gordin-sap** [comment] 2021-11-21 10:10
Hi @werne2j, I have the same issue. We already use Helm and I am trying to add argocd-vault-plugin. 
Don't we have some simple solution for this issue meanwhile?

**Comment by ira-gordin-sap** [comment] 2021-11-21 10:36
Hi @clcchai, did you succeed to create the app using both argocd-vault-plugin and helm?

**Comment by werne2j** [comment] 2021-11-21 13:19
The solution described above or in the docs here (https://ibm.github.io/argocd-vault-plugin/v1.5.0/usage/#with-helm) is going to be the best bet. This is something we do in production and it works pretty well. There isn’t really much more that can be done because of limitations of Argo CD.

This issue https://github.com/argoproj/argo-cd/issues/7623 could make this easier once done but again that is something we can’t control

**Comment by ira-gordin-sap** [comment] 2021-11-21 15:52
@werne2j may I pass environment to helm here (https://ibm.github.io/argocd-vault-plugin/v1.5.0/usage/#with-helm) ?

**Comment by ira-gordin-sap** [comment] 2021-11-22 12:04
@werne2j 
Is the following from [plugin](https://ibm.github.io/argocd-vault-plugin/v1.5.0/usage/#with-helm):
Helm args must be defined in the application manifest:
  source:
    path: your-app
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: helm_args
          value: -f values-dev.yaml -f values-dev-tag.yaml
instead the following in Argo CD application with Helm:
  source:
    path: your-app
    helm:
      valueFiles:
      - values-dev.yaml 
      - values-dev-tag.yaml

**Comment by ira-gordin-sap** [comment] 2021-11-25 14:56
Hi @werne2j,
I applied the solution with (https://ibm.github.io/argocd-vault-plugin/v1.5.0/usage/#with-helm) as you advised.
I had some issue [with missing helm repository](https://github.com/IBM/argocd-vault-plugin/issues/175#issuecomment-977847761).
Currently I have another issue.
One of my applications/charts uses velero chart which have the following job:
```
kind: Job
metadata:
  name: {{ template "velero.fullname" . }}-upgrade-crds
  namespace: {{ .Release.Namespace }}
```
The issue is that when I am using my solution with argocd-vault-plugin-helm, 
this Job is created with argocd namespace and not velero namespace as expected and it causes other issues. 
All other k8s velero objects are created with velero namespace as expected.
Could you please advise?

**Comment by ira-gordin-sap** [comment] 2021-11-25 15:53
Hi @werne2j, I've fixed this issue by adding ```--namespace=velero``` to ```helm_args``` in the following way:  
```
plugin:
      env:
      - name: helm_args
        value: --namespace=velero -f values.yaml
      name: argocd-vault-plugin-helm
```

Now it looks like works properly but I wonder if all the issues solved.

**Comment by ira-gordin-sap** [comment] 2021-11-29 11:34
@werne2j maybe you can advise where I can find the full list of the "--" parameters Argo CD sends to helm, so I'll be able to align with it when using argocd-vault-plugin-helm?

**Comment by werne2j** [comment] 2021-11-29 13:20
@ira-gordin-sap That is really up to you on how you want to construct the `plugin` within the argocd-cm file. We do this `helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE $HELM_ARGS . | argocd-vault-plugin generate -` on my team and it works well. `ARGOCD_APP_NAME` and `ARGOCD_APP_NAMESPACE` are Env Vars that come from Argo CD (https://argo-cd.readthedocs.io/en/stable/user-guide/build-environment/) you can find the helm template docs here https://helm.sh/docs/helm/helm_template/

**Comment by ira-gordin-sap** [comment] 2021-11-30 10:54
@werne2j Thanks. Hope it will always work in all our charts. I think it is a good idea to add ```-n $ARGOCD_APP_NAMESPACE``` to https://ibm.github.io/argocd-vault-plugin/v1.5.0/usage/#with-helm but I am not sure how to manage it.

**Comment by ira-gordin-sap** [comment] 2021-12-01 13:44
@werne2j Are you using AppRole to auth to Vault? Which values for secret_id_num_uses, token_num_uses, token_max_ttl, token_ttl, etc. are required in order the plugin will work as expected.

**Comment by werne2j** [comment] 2021-12-01 19:49
If you look here https://github.com/IBM/argocd-vault-plugin/blob/main/pkg/config/config.go#L77 the values required for AppRole to work are
```
AVP_ROLE_ID: Your AppRole Role ID
AVP_SECRET_ID: Your AppRole Secret ID
```
to go along with the other required values https://argocd-vault-plugin.readthedocs.io/en/stable/backends/#approle-authentication

**Comment by ira-gordin-sap** [comment] 2021-12-02 07:54
@werne2j I am talking about the parameters for creating AppRole in Vault

**Comment by werne2j** [comment] 2021-12-02 13:29
I would follow the vault docs https://www.vaultproject.io/docs/auth/approle but the only thing required for working with AVP is that the AppRole must have `read` and `list` permissions on the path you are providing in your yamls. You can see how we do it in our tests https://github.com/IBM/argocd-vault-plugin/blob/main/pkg/helpers/test_helpers.go#L146 as we are setting up a test vault with approle. Hope that helps.

**Comment by ira-gordin-sap** [comment] 2021-12-06 10:59
@werne2j It works with ```read``` without ```list```, but maybe I miss something. Why is ```list``` needed?

**Comment by ira-gordin-sap** [comment] 2022-01-05 10:05
> @ira-gordin-sap That is really up to you on how you want to construct the `plugin` within the argocd-cm file. We do this `helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE $HELM_ARGS . | argocd-vault-plugin generate -` on my team and it works well. `ARGOCD_APP_NAME` and `ARGOCD_APP_NAMESPACE` are Env Vars that come from Argo CD (https://argo-cd.readthedocs.io/en/stable/user-guide/build-environment/) you can find the helm template docs here https://helm.sh/docs/helm/helm_template/

> @werne2j Thanks. Hope it will always work in all our charts. I think it is a good idea to add `-n $ARGOCD_APP_NAMESPACE` to https://ibm.github.io/argocd-vault-plugin/v1.5.0/usage/#with-helm but I am not sure how to manage it.

@werne2j We just found that `--include-crds` flag is required for `helm template` command. Thanks to my colleague

**Comment by bobertrublik** [comment] 2022-01-27 08:47
> > @ira-gordin-sap That is really up to you on how you want to construct the `plugin` within the argocd-cm file. We do this `helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE $HELM_ARGS . | argocd-vault-plugin generate -` on my team and it works well. `ARGOCD_APP_NAME` and `ARGOCD_APP_NAMESPACE` are Env Vars that come from Argo CD (https://argo-cd.readthedocs.io/en/stable/user-guide/build-environment/) you can find the helm template docs here https://helm.sh/docs/helm/helm_template/
> 
> > @werne2j Thanks. Hope it will always work in all our charts. I think it is a good idea to add `-n $ARGOCD_APP_NAMESPACE` to https://ibm.github.io/argocd-vault-plugin/v1.5.0/usage/#with-helm but I am not sure how to manage it.
> 
> @werne2j We just found that `--include-crds` flag is required for `helm template` command. Thanks to my colleague @guymeronorange_heart🙏🏻 So it should be `helm template --include-crds $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE $BAS_APP_HELM_ARGS . | argocd-vault-plugin generate -`

I have come to the same result and it works pretty great for upstream Helm charts. Do you maybe have an idea how to add custom configmaps or secrets (in the same directory as the Helm value files in $helm_args) to the template output without creating a new Argo Application?

**Comment by maxisam** [comment] 2022-03-20 05:53
Hi I am using the same script 

```sh
helm template $ARGOCD_APP_NAME -n $ARGOCD_APP_NAMESPACE $HELM_ARGS . | argocd-vault-plugin generate -
```

and my HELM_ARGS  is `-f values.yml`

It seems like it can't get the file properly. I got file not found error

Any help?

**Comment by ira-gordin-sap** [comment] 2022-09-06 11:13
> I think the "usage" page in the documentation should be updated to include an example with `-n $ARGOCD_APP_NAMESPACE`

exactly as I asked https://github.com/argoproj-labs/argocd-vault-plugin/issues/101#issuecomment-982520521
